import React from "react";
import { StyleSheet, ScrollView } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { ThemedText } from "@/components/ThemedText";
import { ThemedView } from "@/components/ThemedView";
import { Card } from "@/components/Card";
import { useTheme } from "@/hooks/useTheme";
import { Spacing, BorderRadius } from "@/constants/theme";

export default function PrivacyPolicyScreen() {
  const { theme } = useTheme();
  const insets = useSafeAreaInsets();

  return (
    <ThemedView style={styles.container}>
      <ScrollView
        contentContainerStyle={[
          styles.content,
          { paddingBottom: insets.bottom + Spacing["3xl"] },
        ]}
        showsVerticalScrollIndicator={false}
      >
        <ThemedText
          type="small"
          style={[styles.lastUpdated, { color: theme.textSecondary }]}
        >
          Last Updated: April 2026
        </ThemedText>

        <Card style={styles.section}>
          <ThemedText type="h3" style={styles.sectionTitle}>
            Introduction
          </ThemedText>
          <ThemedText type="body" style={styles.paragraph}>
            Welcome to StudyMind. This privacy policy explains what information
            we collect, how we use it, and the choices you have. We believe in
            being straightforward about our data practices.
          </ThemedText>
          <ThemedText type="body" style={styles.paragraph}>
            StudyMind helps you turn recordings, images, and text into organized
            study materials like notes, flashcards, and quizzes. You can use the
            app in guest mode without creating an account.
          </ThemedText>
        </Card>

        <Card style={styles.section}>
          <ThemedText type="h3" style={styles.sectionTitle}>
            Information We Collect
          </ThemedText>
          <ThemedText type="body" style={styles.paragraph}>
            <ThemedText style={styles.bold}>Audio Recordings:</ThemedText> When
            you record audio or upload audio files, the audio is sent to our
            server for AI-powered transcription. The audio is processed
            temporarily and the resulting text is returned to your device.
          </ThemedText>
          <ThemedText type="body" style={styles.paragraph}>
            <ThemedText style={styles.bold}>Images:</ThemedText> When you
            capture photos of notes, textbooks, or whiteboards, or select images
            from your gallery, they are sent to our server for text extraction
            (OCR). The images are processed temporarily and the extracted text is
            returned to your device.
          </ThemedText>
          <ThemedText type="body" style={styles.paragraph}>
            <ThemedText style={styles.bold}>Text Input:</ThemedText> When you
            paste text from your clipboard, upload text files, or type content
            directly, that text is sent to our server for AI processing to
            generate study materials.
          </ThemedText>
          <ThemedText type="body" style={styles.paragraph}>
            <ThemedText style={styles.bold}>Study Content:</ThemedText> Notes,
            flashcards, quizzes, and other study materials generated by the app
            are stored locally on your device.
          </ThemedText>
          <ThemedText type="body" style={styles.paragraph}>
            <ThemedText style={styles.bold}>App Preferences:</ThemedText>{" "}
            Settings such as your preferred language, notification preferences,
            and theme choice are stored locally on your device.
          </ThemedText>
        </Card>

        <Card style={styles.section}>
          <ThemedText type="h3" style={styles.sectionTitle}>
            Where Your Data Is Stored
          </ThemedText>
          <ThemedText type="body" style={styles.paragraph}>
            <ThemedText style={styles.bold}>On Your Device:</ThemedText> The
            majority of your data lives on your device. This includes study
            materials, course organization, app settings, and notification
            schedules. There is no cross-device sync.
          </ThemedText>
          <ThemedText type="body" style={styles.paragraph}>
            <ThemedText style={styles.bold}>On Our Server:</ThemedText> Audio,
            images, and text are sent to our server only when you use AI
            features. This data is processed temporarily and the results are
            returned to your device. We do not permanently store your audio,
            images, or text after processing is complete.
          </ThemedText>
        </Card>

        <Card style={styles.section}>
          <ThemedText type="h3" style={styles.sectionTitle}>
            How We Use Your Information
          </ThemedText>
          <ThemedText type="body" style={styles.paragraph}>
            We use your information solely to provide the app's core features:
          </ThemedText>
          <ThemedText type="body" style={styles.listItem}>
            - Transcribe audio recordings into text
          </ThemedText>
          <ThemedText type="body" style={styles.listItem}>
            - Extract text from images using OCR
          </ThemedText>
          <ThemedText type="body" style={styles.listItem}>
            - Generate study notes, flashcards, and quizzes from your content
          </ThemedText>
          <ThemedText type="body" style={styles.listItem}>
            - Summarize text content you provide
          </ThemedText>
          <ThemedText type="body" style={styles.paragraph}>
            We do not use your data for advertising, analytics, profiling, or
            any purpose other than providing the features you use within the app.
          </ThemedText>
        </Card>

        <Card style={styles.section}>
          <ThemedText type="h3" style={styles.sectionTitle}>
            Third-Party Services
          </ThemedText>
          <ThemedText type="body" style={styles.listItem}>
            - <ThemedText style={styles.bold}>OpenAI:</ThemedText> Audio,
            images, and text you submit for AI processing are sent to OpenAI for
            transcription, text extraction, and study material generation.
          </ThemedText>
          <ThemedText type="body" style={styles.listItem}>
            - <ThemedText style={styles.bold}>Google Play:</ThemedText> In-app
            purchases are processed by Google Play. Payment information is
            handled entirely by Google and is never collected or stored by
            StudyMind.
          </ThemedText>
          <ThemedText type="body" style={styles.paragraph}>
            We do not sell, rent, or share your personal data with any other
            third parties.
          </ThemedText>
        </Card>

        <Card style={styles.section}>
          <ThemedText type="h3" style={styles.sectionTitle}>
            Notifications
          </ThemedText>
          <ThemedText type="body" style={styles.paragraph}>
            StudyMind can send study reminders as local notifications on your
            device. Notifications are optional and not enabled by default. You
            can enable, disable, or customize them at any time in Settings. All
            notification scheduling happens locally on your device. No
            notification data is sent to our servers.
          </ThemedText>
        </Card>

        <Card style={styles.section}>
          <ThemedText type="h3" style={styles.sectionTitle}>
            Data Deletion
          </ThemedText>
          <ThemedText type="body" style={styles.paragraph}>
            You have three options for deleting your data:
          </ThemedText>
          <ThemedText type="body" style={styles.listItem}>
            - <ThemedText style={styles.bold}>Clear All Data</ThemedText>{" "}
            (Settings): Deletes all study data from your device only. Server
            data is not affected.
          </ThemedText>
          <ThemedText type="body" style={styles.listItem}>
            - <ThemedText style={styles.bold}>Delete My Data</ThemedText>{" "}
            (Settings, then Privacy & Data): Deletes all study content from both
            the server and your device. Your account remains active but empty.
          </ThemedText>
          <ThemedText type="body" style={styles.listItem}>
            - <ThemedText style={styles.bold}>Delete Account</ThemedText>{" "}
            (Settings): Deletes your account and all data from both the server
            and your device, including purchase history.
          </ThemedText>
          <ThemedText type="body" style={styles.paragraph}>
            All deletion actions are permanent and cannot be undone. You can also
            request deletion by emailing us.
          </ThemedText>
        </Card>

        <Card style={styles.section}>
          <ThemedText type="h3" style={styles.sectionTitle}>
            Your Rights and Controls
          </ThemedText>
          <ThemedText type="body" style={styles.listItem}>
            - <ThemedText style={styles.bold}>Delete your data</ThemedText> at
            any time using the options described above
          </ThemedText>
          <ThemedText type="body" style={styles.listItem}>
            - <ThemedText style={styles.bold}>Export your content</ThemedText>{" "}
            as PDF or text files using the share feature
          </ThemedText>
          <ThemedText type="body" style={styles.listItem}>
            -{" "}
            <ThemedText style={styles.bold}>Manage notifications</ThemedText> by
            enabling or disabling study reminders in Settings
          </ThemedText>
          <ThemedText type="body" style={styles.listItem}>
            - <ThemedText style={styles.bold}>Use guest mode</ThemedText>{" "}
            without creating an account or providing personal information
          </ThemedText>
        </Card>

        <Card style={styles.section}>
          <ThemedText type="h3" style={styles.sectionTitle}>
            Data Security
          </ThemedText>
          <ThemedText type="body" style={styles.paragraph}>
            We take reasonable measures to protect your information. Data
            transmitted between the app and our server is encrypted in transit.
            Study content on your device is protected by your device's built-in
            security features. We do not store your audio, images, or text on
            our servers longer than necessary to complete processing.
          </ThemedText>
        </Card>

        <Card style={styles.section}>
          <ThemedText type="h3" style={styles.sectionTitle}>
            {"Children's Privacy"}
          </ThemedText>
          <ThemedText type="body" style={styles.paragraph}>
            StudyMind is intended for users aged 13 and older. We do not
            knowingly collect personal information from children under 13. If
            you believe a child under 13 has provided us with personal
            information, please contact us.
          </ThemedText>
        </Card>

        <Card style={styles.section}>
          <ThemedText type="h3" style={styles.sectionTitle}>
            Changes to This Policy
          </ThemedText>
          <ThemedText type="body" style={styles.paragraph}>
            We may update this privacy policy from time to time. When we make
            changes, we will update the "Last Updated" date at the top of this
            page.
          </ThemedText>
        </Card>

        <Card style={styles.section}>
          <ThemedText type="h3" style={styles.sectionTitle}>
            Contact Us
          </ThemedText>
          <ThemedText type="body" style={styles.paragraph}>
            If you have questions about this privacy policy or your data, please
            contact us at:
          </ThemedText>
          <ThemedText
            type="body"
            style={[styles.paragraph, { color: theme.link }]}
          >
            studymindv1@hotmail.com
          </ThemedText>
        </Card>
      </ScrollView>
    </ThemedView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    padding: Spacing.lg,
  },
  lastUpdated: {
    marginBottom: Spacing.lg,
    textAlign: "center",
  },
  section: {
    marginBottom: Spacing.lg,
  },
  sectionTitle: {
    marginBottom: Spacing.md,
  },
  paragraph: {
    lineHeight: 22,
    marginBottom: Spacing.sm,
  },
  bold: {
    fontWeight: "600",
  },
  listItem: {
    lineHeight: 22,
    marginBottom: Spacing.xs,
    paddingLeft: Spacing.sm,
  },
});
