#!/usr/bin/env node
/**
 * Handoff Script
 * - Runs audit:fast (skip build, verify artifacts + probes)
 * - Ensures REPORT_FOR_CHATGPT.md exists
 * - Writes PROMPT_FOR_AGENT.txt with a fixed instruction prompt
 *
 * Usage:
 *   node scripts/handoff.cjs
 */

const { execSync } = require("node:child_process");
const fs = require("node:fs");
const path = require("node:path");

const ROOT = process.cwd();

function log(msg) {
  process.stdout.write(`${msg}\n`);
}

function fail(msg) {
  process.stderr.write(`FAIL: ${msg}\n`);
  process.exit(1);
}

log("=== Handoff: audit + report + prompt ===\n");

log("Step 1: Running audit (skip build)...\n");
try {
  execSync("AUDIT_SKIP_BUILD=1 node scripts/audit.cjs", {
    stdio: "inherit",
    timeout: 120_000,
  });
} catch (e) {
  fail(`Audit failed with exit code ${e.status}. Fix issues before handoff.`);
}

const reportPath = path.join(ROOT, "REPORT_FOR_CHATGPT.md");
if (!fs.existsSync(reportPath)) {
  fail("REPORT_FOR_CHATGPT.md was not generated by audit.");
}
log("\nStep 2: REPORT_FOR_CHATGPT.md confirmed.");

const reportContent = fs.readFileSync(reportPath, "utf-8");

const prompt = `You are a senior production engineer.

You are given the following production audit report.

<REPORT>
${reportContent}
</REPORT>

Your job:

1) Read the report completely.
2) Identify any:
   - FAILED probes
   - Missing artifacts
   - Unexpected route behavior
   - Risky environment variable usage
   - Deployment risks
3) Propose precise file changes to fix issues.
4) Do NOT redesign architecture unless absolutely necessary.
5) Maintain:
   - Expo web export -> dist/
   - server_dist/index.mjs production server
   - No Metro in production
   - PORT binding via process.env.PORT
6) If audit passed, suggest:
   - reliability improvements
   - performance optimizations
   - security hardening
   - SEO improvements (robots.txt, sitemap.xml, meta tags)
7) Output:
   - Exact files to modify
   - Precise diffs or complete replacements
   - Any new scripts required
   - Any new environment variable names (names only, no values)

Rules:
- Do not guess.
- Do not remove working behavior.
- Prefer minimal, deterministic changes.
- Keep deployment compatible with Cloud Run / Replit.
`;

const promptPath = path.join(ROOT, "PROMPT_FOR_AGENT.txt");
fs.writeFileSync(promptPath, prompt);
log(`Step 3: PROMPT_FOR_AGENT.txt written (${prompt.length} chars).`);

log("\n=== Handoff complete ===");
log("Files ready:");
log(`  - ${reportPath}`);
log(`  - ${promptPath}`);
