import * as Sharing from "expo-sharing";
import * as FileSystem from "expo-file-system/legacy";
import * as Print from "expo-print";
import * as Clipboard from "expo-clipboard";
import { Platform } from "react-native";

export type ShareResult = { method: "shared" | "copied" | "downloaded" };

export async function shareOrDownload(options: {
  html: string;
  plainText: string;
  title: string;
}): Promise<ShareResult> {
  const { html, plainText, title } = options;

  if (Platform.OS === "web") {
    await Clipboard.setStringAsync(plainText);
    return { method: "copied" };
  }

  try {
    const { uri } = await Print.printToFileAsync({ html, base64: false });
    const isAvailable = await Sharing.isAvailableAsync();
    if (isAvailable) {
      await Sharing.shareAsync(uri, {
        mimeType: "application/pdf",
        dialogTitle: `Share ${title}`,
      });
      return { method: "shared" };
    }
    await Clipboard.setStringAsync(plainText);
    return { method: "copied" };
  } catch {
    await Clipboard.setStringAsync(plainText);
    return { method: "copied" };
  }
}

export interface ExportableNote {
  title: string;
  content: string;
  lectureTitle: string;
  topicName?: string;
  courseName?: string;
  createdAt: string;
}

export interface ExportableFlashcard {
  front: string;
  back: string;
  difficulty: number;
  interval: number;
  nextReview?: string;
}

export interface ExportData {
  type: "notes" | "flashcards" | "all";
  notes?: ExportableNote[];
  flashcards?: ExportableFlashcard[];
  lectureTitle: string;
  courseName?: string;
  topicName?: string;
}

function escapeHtml(text: string | undefined | null): string {
  if (!text) return "";
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;")
    .replace(/\n/g, "<br>");
}

function formatMarkdown(text: string | undefined | null): string {
  if (!text) return "";
  let html = escapeHtml(text);
  html = html.replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>");
  html = html.replace(/\*(.*?)\*/g, "<em>$1</em>");
  html = html.replace(/^- (.+)/gm, "<li>$1</li>");
  html = html.replace(/^(\d+)\. (.+)/gm, "<li>$2</li>");
  return html;
}

export function generateNotesHtml(data: ExportData): string {
  const notes = data.notes || [];

  const notesHtml = notes
    .map(
      (note) => `
    <div class="note">
      <h2>${escapeHtml(note.title)}</h2>
      <p class="meta">${note.topicName ? `${note.topicName} • ` : ""}${new Date(note.createdAt).toLocaleDateString()}</p>
      <div class="content">${formatMarkdown(note.content)}</div>
    </div>
  `,
    )
    .join("");

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(data.lectureTitle)} - Notes</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
    h1 {
      color: #6366F1;
      border-bottom: 2px solid #E5E7EB;
      padding-bottom: 10px;
    }
    h2 {
      color: #374151;
      margin-top: 30px;
    }
    .meta {
      color: #6B7280;
      font-size: 0.9em;
      margin-bottom: 15px;
    }
    .header-meta {
      color: #6B7280;
      font-size: 0.95em;
      margin-bottom: 30px;
    }
    .note {
      margin-bottom: 40px;
      padding-bottom: 20px;
      border-bottom: 1px solid #E5E7EB;
    }
    .content {
      background: #F9FAFB;
      padding: 15px;
      border-radius: 8px;
    }
    li {
      margin-left: 20px;
      margin-bottom: 5px;
    }
    strong {
      color: #1F2937;
    }
    .footer {
      margin-top: 40px;
      text-align: center;
      color: #9CA3AF;
      font-size: 0.85em;
    }
  </style>
</head>
<body>
  <h1>${escapeHtml(data.lectureTitle)}</h1>
  <p class="header-meta">
    ${data.courseName ? `Course: ${escapeHtml(data.courseName)}<br>` : ""}
    ${data.topicName ? `Topic: ${escapeHtml(data.topicName)}<br>` : ""}
    Exported: ${new Date().toLocaleDateString()}
  </p>
  ${notesHtml}
  <div class="footer">
    Generated by StudyMind
  </div>
</body>
</html>
`;
}

export function generateFlashcardsHtml(data: ExportData): string {
  const flashcards = data.flashcards || [];

  const flashcardsHtml = flashcards
    .map(
      (card, index) => `
    <div class="flashcard">
      <div class="card-number">${index + 1}</div>
      <div class="front">
        <strong>Q:</strong> ${formatMarkdown(card.front)}
      </div>
      <div class="back">
        <strong>A:</strong> ${formatMarkdown(card.back)}
      </div>
      <div class="card-meta">
        Difficulty: ${card.difficulty.toFixed(2)} | Interval: ${card.interval} days
        ${card.nextReview ? ` | Next Review: ${new Date(card.nextReview).toLocaleDateString()}` : ""}
      </div>
    </div>
  `,
    )
    .join("");

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(data.lectureTitle)} - Flashcards</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
    h1 {
      color: #6366F1;
      border-bottom: 2px solid #E5E7EB;
      padding-bottom: 10px;
    }
    .header-meta {
      color: #6B7280;
      font-size: 0.95em;
      margin-bottom: 30px;
    }
    .flashcard {
      background: #fff;
      border: 1px solid #E5E7EB;
      border-radius: 12px;
      padding: 20px;
      margin-bottom: 20px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.05);
    }
    .card-number {
      background: #6366F1;
      color: white;
      width: 28px;
      height: 28px;
      border-radius: 14px;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      font-size: 0.85em;
      font-weight: 600;
      margin-bottom: 12px;
    }
    .front {
      background: #F0F9FF;
      padding: 15px;
      border-radius: 8px;
      margin-bottom: 12px;
    }
    .back {
      background: #F0FDF4;
      padding: 15px;
      border-radius: 8px;
      margin-bottom: 12px;
    }
    .card-meta {
      color: #9CA3AF;
      font-size: 0.8em;
      text-align: right;
    }
    .count {
      background: #6366F1;
      color: white;
      padding: 4px 12px;
      border-radius: 12px;
      font-size: 0.9em;
    }
    .footer {
      margin-top: 40px;
      text-align: center;
      color: #9CA3AF;
      font-size: 0.85em;
    }
  </style>
</head>
<body>
  <h1>${escapeHtml(data.lectureTitle)} <span class="count">${flashcards.length} cards</span></h1>
  <p class="header-meta">
    ${data.courseName ? `Course: ${escapeHtml(data.courseName)}<br>` : ""}
    ${data.topicName ? `Topic: ${escapeHtml(data.topicName)}<br>` : ""}
    Exported: ${new Date().toLocaleDateString()}
  </p>
  ${flashcardsHtml}
  <div class="footer">
    Generated by StudyMind
  </div>
</body>
</html>
`;
}

export function generateCombinedHtml(data: ExportData): string {
  const notes = data.notes || [];
  const flashcards = data.flashcards || [];

  const notesHtml =
    notes.length > 0
      ? `
    <h2>Notes</h2>
    ${notes
      .map(
        (note) => `
      <div class="note">
        <h3>${escapeHtml(note.title)}</h3>
        <div class="content">${formatMarkdown(note.content)}</div>
      </div>
    `,
      )
      .join("")}
  `
      : "";

  const flashcardsHtml =
    flashcards.length > 0
      ? `
    <h2>Flashcards <span class="count">${flashcards.length}</span></h2>
    ${flashcards
      .map(
        (card, index) => `
      <div class="flashcard">
        <div class="card-number">${index + 1}</div>
        <div class="front"><strong>Q:</strong> ${formatMarkdown(card.front)}</div>
        <div class="back"><strong>A:</strong> ${formatMarkdown(card.back)}</div>
      </div>
    `,
      )
      .join("")}
  `
      : "";

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(data.lectureTitle)} - Study Materials</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
    h1 { color: #6366F1; border-bottom: 2px solid #E5E7EB; padding-bottom: 10px; }
    h2 { color: #374151; margin-top: 40px; border-bottom: 1px solid #E5E7EB; padding-bottom: 8px; }
    h3 { color: #4B5563; }
    .header-meta { color: #6B7280; font-size: 0.95em; margin-bottom: 30px; }
    .note { margin-bottom: 30px; }
    .content { background: #F9FAFB; padding: 15px; border-radius: 8px; }
    .flashcard { background: #fff; border: 1px solid #E5E7EB; border-radius: 12px; padding: 20px; margin-bottom: 20px; }
    .card-number { background: #6366F1; color: white; width: 28px; height: 28px; border-radius: 14px; display: inline-flex; align-items: center; justify-content: center; font-size: 0.85em; font-weight: 600; margin-bottom: 12px; }
    .front { background: #F0F9FF; padding: 15px; border-radius: 8px; margin-bottom: 12px; }
    .back { background: #F0FDF4; padding: 15px; border-radius: 8px; }
    .count { background: #6366F1; color: white; padding: 4px 12px; border-radius: 12px; font-size: 0.8em; margin-left: 10px; }
    .footer { margin-top: 40px; text-align: center; color: #9CA3AF; font-size: 0.85em; }
  </style>
</head>
<body>
  <h1>${escapeHtml(data.lectureTitle)}</h1>
  <p class="header-meta">
    ${data.courseName ? `Course: ${escapeHtml(data.courseName)}<br>` : ""}
    ${data.topicName ? `Topic: ${escapeHtml(data.topicName)}<br>` : ""}
    Exported: ${new Date().toLocaleDateString()}
  </p>
  ${notesHtml}
  ${flashcardsHtml}
  <div class="footer">
    Generated by StudyMind
  </div>
</body>
</html>
`;
}

export async function exportToPdf(data: ExportData): Promise<string | null> {
  try {
    let html: string;
    switch (data.type) {
      case "notes":
        html = generateNotesHtml(data);
        break;
      case "flashcards":
        html = generateFlashcardsHtml(data);
        break;
      case "all":
        html = generateCombinedHtml(data);
        break;
    }

    const { uri } = await Print.printToFileAsync({
      html,
      base64: false,
    });

    return uri;
  } catch (error) {
    console.error("Error exporting to PDF:", error);
    return null;
  }
}

export async function shareContent(data: ExportData): Promise<boolean> {
  try {
    const isAvailable = await Sharing.isAvailableAsync();
    if (!isAvailable) {
      console.log("Sharing is not available on this device");
      return false;
    }

    const pdfPath = await exportToPdf(data);
    if (!pdfPath) {
      return false;
    }

    await Sharing.shareAsync(pdfPath, {
      mimeType: "application/pdf",
      dialogTitle: `Share ${data.lectureTitle}`,
    });

    return true;
  } catch (error) {
    console.error("Error sharing content:", error);
    return false;
  }
}

export function generatePlainText(data: ExportData): string {
  const lines: string[] = [];

  lines.push(`${data.lectureTitle}`);
  lines.push("=".repeat(data.lectureTitle.length));
  if (data.courseName) lines.push(`Course: ${data.courseName}`);
  if (data.topicName) lines.push(`Topic: ${data.topicName}`);
  lines.push(`Exported: ${new Date().toLocaleDateString()}`);
  lines.push("");

  if (data.notes && data.notes.length > 0) {
    lines.push("NOTES");
    lines.push("-".repeat(40));
    data.notes.forEach((note) => {
      lines.push(`\n## ${note.title}\n`);
      lines.push(note.content);
      lines.push("");
    });
  }

  if (data.flashcards && data.flashcards.length > 0) {
    lines.push("\nFLASHCARDS");
    lines.push("-".repeat(40));
    data.flashcards.forEach((card, i) => {
      lines.push(`\n${i + 1}. Q: ${card.front}`);
      lines.push(`   A: ${card.back}`);
    });
  }

  lines.push("\n---");
  lines.push("Generated by StudyMind");

  return lines.join("\n");
}

export async function exportToText(data: ExportData): Promise<string | null> {
  try {
    const text = generatePlainText(data);
    const filename = `${data.lectureTitle.replace(/[^a-zA-Z0-9]/g, "_")}_${data.type}.txt`;
    const path = `${FileSystem.documentDirectory}${filename}`;

    await FileSystem.writeAsStringAsync(path, text, {
      encoding: FileSystem.EncodingType.UTF8,
    });

    return path;
  } catch (error) {
    console.error("Error exporting to text:", error);
    return null;
  }
}

export async function shareAsText(data: ExportData): Promise<boolean> {
  try {
    const isAvailable = await Sharing.isAvailableAsync();
    if (!isAvailable) {
      return false;
    }

    const textPath = await exportToText(data);
    if (!textPath) {
      return false;
    }

    await Sharing.shareAsync(textPath, {
      mimeType: "text/plain",
      dialogTitle: `Share ${data.lectureTitle}`,
    });

    return true;
  } catch (error) {
    console.error("Error sharing as text:", error);
    return false;
  }
}
